config/routes.rb
Rails.application.routes.draw do
  devise_for :patrons, controllers: {
    sessions: 'patrons/sessions',
    registrations: 'patrons/registrations'
  }
  resources :raspberry_pi_statuses
  resources :raspberry_pi_updates do
    collection do
      get :latest
      get :version
      get :files
    end
  end

  resources :stripe_webhooks, :path => "stripe-webhooks", :only => [] do
    collection do
      post :webhook, path: ""
    end
  end

  # namespace :manager do
  #   resources :printers
  # end
  resources :item_screen_types 
  
  resources :orders, :only => [:index, :show]
  resources :restaurants, :only => [:show], :path => "" do
    member do
      get :order
      get :welcome
      resources :checkouts, only: [:index, :create] do
        collection do
          get :pay
          post :pay
          post :stripe
          resources :receipt, only: [], param: :uuid do
            member do
              get :show, to: "checkouts#receipt"
            end
          end
        end
      end
    end
  end

  resources :patrons, :module => :patrons, :only => [:index, :show] do
    collection do
      get :settings, :to => "patrons#show"
      resources :orders, :only => [:index]
      resources :patron_allergens, :only => [:update]
      resources :patron_marketing_preferences, :only => [:update]
    end
  end

  resources :receipts do 
    post 'is_ready'
    post 'is_item_ready/:screen_item_id', to: 'receipts#is_item_ready', as: :screen_item_ready
    post 'is_items_ready/:receipt_id/item_screen_type_key/:item_screen_type_key', to: 'receipts#is_items_ready', as: :screen_items_ready
    post 'item_creation_broadcast'
    post 'creation_broadcast'
    collection do 
      get 'view_receipt/:uuid', to: 'receipts#view_receipt', as: :view_receipt
    end
  end
  namespace :restaurant do
    get 'list' => "home#index"
    get 'booking/:slug' => "booking#index", as: :booking
    get 'menu/:slug' => "menu#index", as: :menu

    resources :menu, :only => [:index]

  end



  resources :tables do
    post 'add_item/:menu_id' => 'tables#add_item', as: :add_item
    get 'pay'
    post 'stripe'
    get 'finish'
    get 'manager_finish'
    # get 'sectioned_menus'
    get 'sectioned_menus/:menu_id' => 'tables#show', as: 'sectioned_menus_choice'

  end
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  namespace :api do
    namespace :v1 do
      get 'menu/:id' => 'menu#index'
      get 'menu_item/:id', to: 'menu#menu_item'
      get 'menu_optionals', to: 'menu#menu_optionals'
      get 'menu_optionals/:items', to: 'menu#menu_optionals'
    end
  end
  namespace :manager do
    resources :restaurants, :param => :restaurant_id do
      member do
        resources :discount_codes
        resources :orders, :only => [] do
          member do
            resources :refunds, only: [:create]
          end
        end
      end
      collection do
        resources :administrations, :only => [:index] do
          member do
            get :login_as
          end
        end
        resources :reports, :only => [:index]
      end
    end
    resources :home do
      collection do
        get :dashboard
        get :menu
      end
    end

    get 'live_tables/:restaurant_id' => 'live#tables', as: :live_tables
    get 'live_items/:restaurant_id' => 'live#items', as: :live_items
    get 'live_orders/:restaurant_id' => 'live#orders', as: :live_orders
    get 'live_orders/broadcast/:restaurant_id' => 'live#orders_broadcast', as: :live_orders_broadcast
    get 'live_food/:restaurant_id' => 'live#food', as: :live_food
    get 'live_food/broadcast/:restaurant_id' => 'live#orders_broadcast', as: :live_food_broadcast
    get 'live_drinks/:restaurant_id' => 'live#drinks', as: :live_drinks
    get 'live_drinks/broadcast/:restaurant_id' => 'live#orders_broadcast', as: :live_drinks_broadcast
    get 'receipts/:restaurant_id' => 'live#receipts', as: :receipts
    get 'send_receipt/:receipt_id' => 'live#send_receipt', as: :send_receipts
    get 'service/:restaurant_id/item/:table_item_id' => 'live#service', as: :live_service
    get 'ready/:restaurant_id/item/:table_item_id' => 'live#ready', as: :live_ready


    resources :features
    resources :templates  
    resources :settings
    resources :packages do
      post 'add_feature/:feature_id', action: :add_feature, as: :add_feature
      post 'remove_feature/:feature_id', action: :remove_feature, as: :remove_feature
    end

    resources :cuisines
    resources :restaurants do

      post 'set_delay'
      post 'reporting/daily'
      get 'reporting/daily'
      get 'reporting/zreport_show/:daily_reporting_id', to: 'reporting#zreport_show', as: :zreport

      resources :opening_times
      resources :delivery_postcodes

      resources :themes

      resources :item_screens

      resources :pi_interfaces do 
        get :request_lsusb
        resources :printers 
      end
      post 'add_feature/:feature_id', action: :add_feature, as: :add_feature
      post 'remove_feature/:feature_id', action: :remove_feature, as: :remove_feature
      post 'toggle_feature/:feature_id', action: :toggle_feature, as: :toggle_feature
      get 'active', action: :active
      post 'toggle_active', action: :toggle_active
      post 'add_template', action: :add_template


      resources :menus do
        post :clone
      end
      resources :restaurant_tables do
        collection do
          get :qr
        end
      end
      resources :custom_lists do 
        resources :custom_list_items
        post :up
        post :down
      end
    end
    devise_for :restaurant_users, path: 'manager', controllers: {
      sessions: 'manager/restaurant_users/sessions',
      registrations: 'manager/restaurant_users/registrations',
      passwords: 'manager/restaurant_users/passwords'
    }
  end

  namespace :onboarding do
    resources :restaurants do
      get 'services'
      get 'connect'
      get 'complete'
      post 'toggle_feature/:feature_id', action: :toggle_feature, as: :toggle_feature
      post 'dashboard_login', action: :dashboard_login, as: :dashboard_login
    end
    
    get 'start', to: 'home#start'
    get 'continue', to: 'home#continue'
    patch 'agree', to: 'home#tos_agree'

    devise_for :restaurant_users, path: '/', controllers: {
      sessions: 'onboarding/restaurant_users/sessions',
      registrations: 'onboarding/restaurant_users/registrations',
      passwords: 'onboarding/restaurant_users/passwords'
    }
  end

#printing

get 'receipt/:receipt_id/print/:printer_id', to: 'manager/printers#print', as: :print_receipt
get 'receipt/:receipt_id/screen_item_uuid/:uuid/print/:printer_id', to: 'manager/printers#print_item', as: :print_item_receipt
get 'receipt/:receipt_id/key/:item_screen_type_key/print/:printer_id', to: 'manager/printers#print_items', as: :print_items_receipt


  # get 'order/remove_from_basket/:path/:uuid', to: 'order#remove_from_basket', as: :remove_from_basket
  # get 'order/receipt/:path/:uuid', to: 'order#receipt', as: :order_receipt
  # get 'order/checkout/:path', to: 'order#checkout', as: :checkout
  # post 'order/pay/:path', to: 'order#pay', as: :pay
  # get 'order/checkoutx/:path', to: 'order#checkoutx', as: :checkoutx
  # post 'order/stripe/:path', to: 'order#stripe', as: :stripe
  # get 'order/add_to_basket/:path', to: 'order#add_to_basket', as: :add_to_basket_base
  # get 'order/add_to_basket', to: 'baskets#index', as: :add_to_basket
  get 'baskets/:path/menu/:menu_id/section/:section_id', to: 'baskets#index', as: :order_menu_section
  # get 'order/:path/menu/:menu_id', to: 'restaurants#index', as: :order_menu
  get 'order/:path', to: 'order#index'

  resources :baskets, :only => [:update], param: :path

  get 'home_mobile/index'
  get 'home/index'
  post 'home/register_table'
  get 'home/register_table/:code' => 'home#register_table', as: :register_table
  post 'home/start_table/:table_id' => 'home#start_table', via: %i[get post], as: :start_table
  get 'home/table'
  post 'home/set_locale/:language_id' => 'home#set_locale', as: :home_set_locale

  get '/:name', to: 'restaurant/menu#index'

  root 'home#index'
end

app/models/manager.rb
module Manager
  def self.table_name_prefix
    'manager_'
  end
end

app/controllers/manager/administrations_controller.rb
# frozen_string_literal: true

module Manager
  class AdministrationsController < Manager::BaseController
    before_action :authenticate_manager_restaurant_user!
    before_action :authenticate_admin!

    def index
      @restaurants = Restaurant.includes(:restaurant_user).all
    end

    def login_as
      @restaurant_user = RestaurantUser.find(params[:id])
      sign_in(@restaurant_user)
      redirect_to root_path, notice: "Force signed in successfully"
    end

    private

  end
end

app/controllers/manager/base_controller.rb
# frozen_string_literal: true

module Manager
  class BaseController < ApplicationController
	  alias_method :current_user, :current_manager_restaurant_user # Could be :current_member or :logged_in_user

    layout 'manager'

    rescue_from CanCan::AccessDenied do |exception|
      redirect_to manager_home_index_path, notice: exception.message 
    end


    def set_restaurant
      @restaurant = Restaurant.where(id: params[:restaurant_id]).first || current_manager_restaurant_user.restaurant
      unless current_manager_restaurant_user.id == @restaurant.restaurant_user_id
        redirect_to '/422.html'
      end
    end

    def authenticate_admin!
      current_user.admin ? true : (redirect_to manager_home_index_path, :notice => "Admin level required")
    end
  end

end

app/controllers/manager/custom_list_items_controller.rb
# frozen_string_literal: true

module Manager

class CustomListItemsController < Manager::BaseController
  before_action :authenticate_manager_restaurant_user!
  before_action :set_custom_list_item, only: [:show, :edit, :update, :destroy]
  before_action :set_restaurant
  before_action :set_custom_list
  
  # GET /custom_list_items
  # GET /custom_list_items.json
  def index
    @custom_list_items = CustomListItem.all
  end

  # GET /custom_list_items/1
  # GET /custom_list_items/1.json
  def show
  end

  # GET /custom_list_items/new
  def new
    @custom_list_item = CustomListItem.new
  end

  # GET /custom_list_items/1/edit
  def edit
  end

  # POST /custom_list_items
  # POST /custom_list_items.json
  def create
    @custom_list_item = CustomListItem.new(custom_list_item_params)

    respond_to do |format|
      if @custom_list_item.save
        format.html { redirect_to manager_restaurant_custom_list_path(@restaurant, @custom_list), notice: 'Option Set item was successfully created.' }
        format.json { render :show, status: :created, location: @custom_list_item }
      else
        format.html { render :new }
        format.json { render json: @custom_list_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /custom_list_items/1
  # PATCH/PUT /custom_list_items/1.json
  def update
    
    Rails.cache.delete("api/restaurant/#{@restaurant.id}/menu")
    Rails.cache.delete("restaurant_order_menu_#{@restaurant.id}")

    Rails.cache.delete("custom_list_item_#{@custom_list_item.id}")
    Rails.cache.delete_matched("custom_list_items*-#{@custom_list_item.id}-*")
    Rails.cache.delete("custom_list_#{@custom_list.id}")
    
    respond_to do |format|
      if @custom_list_item.update(custom_list_item_params)
        format.html { redirect_to manager_restaurant_custom_list_path(@restaurant, @custom_list), notice: 'Option Set item was successfully updated.' }
        format.json { render :show, status: :ok, location: @custom_list_item }
      else
        format.html { render :edit }
        format.json { render json: @custom_list_item.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # DELETE /custom_list_items/1
  # DELETE /custom_list_items/1.json
  def destroy
    
    Rails.cache.delete("api/restaurant/#{@restaurant.id}/menu")
    Rails.cache.delete("restaurant_order_menu_#{@restaurant.id}")
    
    Rails.cache.delete("custom_list_item_#{@custom_list_item.id}")
    Rails.cache.delete("custom_list_#{@custom_list.id}")

    clear_list_item(@custom_list.id, @custom_list_item.id)
    @custom_list_item.destroy
    respond_to do |format|
      format.html { redirect_to manager_restaurant_custom_list_path(@restaurant, @custom_list), notice: 'Option Set item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_custom_list_item
      @custom_list_item = CustomListItem.find(params[:id])
    end

    def set_custom_list
      @custom_list = CustomList.find(params[:custom_list_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def custom_list_item_params
      params.require(:custom_list_item).permit(:name, :custom_list_id, :price, :description, :available)
    end

    def clear_list_item(list_id, list_item_id)
      query = Menu.where("custom_lists -> '#{list_id}' ? '#{list_item_id}'")
      query.each do |h|
        h.custom_lists["#{list_id}"].delete("#{list_item_id}")
        h.custom_lists.delete("#{list_id}") if h.custom_lists["#{list_id}"].length == 0
        h.save
      end
    end

  end

end

app/controllers/manager/custom_lists_controller.rb
# frozen_string_literal: true

module Manager

class CustomListsController < Manager::BaseController
  before_action :authenticate_manager_restaurant_user!
  before_action :set_custom_list, only: [:show, :edit, :update, :destroy]
  before_action :set_restaurant

  # GET /custom_lists
  # GET /custom_lists.json
  def index
    @custom_lists = CustomList.where(restaurant_id: @restaurant.id)
  end

  # GET /custom_lists/1
  # GET /custom_lists/1.json
  def show
  end

  # GET /custom_lists/new
  def new
    @custom_list = CustomList.new
    @custom_list.restaurant_id = @restaurant.id
  end

  # GET /custom_lists/1/edit
  def edit
  end

  def up
    @restaurant = Restaurant.find(params[:restaurant_id])
    @custom_list = CustomList.find(params[:custom_list_id])
    @custom_list.move_higher
    @custom_list.save
    redirect_to manager_restaurant_custom_lists_path(@restaurant)
  end

  def down
    @restaurant = Restaurant.find(params[:restaurant_id])
    @custom_list = CustomList.find(params[:custom_list_id])
    @custom_list.move_lower
    @custom_list.save
    redirect_to manager_restaurant_custom_lists_path(@restaurant)
  end

  # POST /custom_lists
  # POST /custom_lists.json
  def create
    @custom_list = CustomList.new(custom_list_params)
    Rails.cache.delete("api/restaurant/#{@restaurant.id}/menu")
    Rails.cache.delete("restaurant_order_menu_#{@restaurant.id}")

    respond_to do |format|
      if @custom_list.save
        format.html { redirect_to manager_restaurant_custom_list_path(@restaurant, @custom_list), notice: 'Option Set was successfully created.' }
        format.json { render :show, status: :created, location: @custom_list }
      else
        format.html { render :new }
        format.json { render json: @custom_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /custom_lists/1
  # PATCH/PUT /custom_lists/1.json
  def update

    Rails.cache.delete("api/restaurant/#{@restaurant.id}/menu")
    Rails.cache.delete("restaurant_order_menu_#{@restaurant.id}")
    
    Rails.cache.delete("custom_list_constraint_#{@custom_list.id}")
    Rails.cache.delete("custom_list_#{@custom_list.id}")
    Rails.cache.delete("custom_list_name_#{@custom_list.id}")
    
    respond_to do |format|
      if @custom_list.update(custom_list_params)
        format.html { redirect_to manager_restaurant_custom_list_path(@restaurant, @custom_list), notice: 'Option Set was successfully updated.' }
        format.json { render :show, status: :ok, location: @custom_list }
      else
        format.html { render :edit }
        format.json { render json: @custom_list.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # DELETE /custom_lists/1
  # DELETE /custom_lists/1.json
  def destroy
    
    Rails.cache.delete("api/restaurant/#{@restaurant.id}/menu")
    Rails.cache.delete("restaurant_order_menu_#{@restaurant.id}")
    
    Rails.cache.delete("custom_list_#{@custom_list.id}")
    Rails.cache.delete("custom_list_name_#{@custom_list.id}")

    @custom_list.destroy
    respond_to do |format|
      format.html { redirect_to manager_restaurant_custom_lists_path(@restaurant), notice: 'Option Set was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_custom_list
      @custom_list = CustomList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def custom_list_params
      params.require(:custom_list).permit(:name, :restaurant_id, :constraint, :required_items, :limit_min, :limit_count, :limit_max)
    end
  end

end

app/controllers/manager/home_controller.rb
# frozen_string_literal: true

module Manager
  class HomeController < Manager::BaseController
    before_action :authenticate_manager_restaurant_user!, except: [:index]

    def index
      @restaurant = current_manager_restaurant_user.restaurant if current_manager_restaurant_user
    end

    def menu
      @restaurant = current_manager_restaurant_user.restaurant
    end

    def dashboard
      @restaurant = current_manager_restaurant_user.restaurant
    end
  end
end

app/views/manager/reporting/_datatable.html.erb
<% content_for :js do %>

<script>
$(document).ready(function() {
  $("#data-<%=by%>").dataTable({
         dom: '<"row pt-4 pb-4"<"col"l><"col"f><"col text-right"B>><"row"<"col"t>><"row"<"col justify-content-center"ip >>',
        buttons: [
            {
                extend: 'excelHtml5',
                title: '<%=daily_reporting.date.strftime("%Y_%B_%d_zreport_by_#{by}_emenunow")%>'
            },
            {
                extend: 'csvHtml5',
                title: '<%=daily_reporting.date.strftime("%Y_%B_%d_zreport_by_#{by}_emenunow")%>'
            }
        ]
  });
});

</script>

<% end %>

<div class='row bg-dark text-light'>
  <div class='col pt-1'>
    <h2>Sales By <%= by.camelcase %> on <%= daily_reporting.date.strftime('%d %B %Y') %></h2>
  </div>
  <div class='col text-right pt-2'>
   <%= link_to 'Back to Daily Reports', manager_restaurant_reporting_daily_path(@restaurant), class: 'btn btn-primary btn-sm' %>
  </div>
</div>

<div class='row'>
  <div class='col'>
    <table class='table table-striped' id='data-<%=by%>'>
      <thead>
        <tr>
          <th>Section</th>
          <th>Item</th>
          <th class='text-right'>Count</th>
          <th class='text-right'>Total</th>
          <th class='text-right'>Percentage Items</th>
          <th class='text-right'>Percentage Sales</th>
        </tr>
      </thead>
      <tbody>
        <% daily_reporting.data.map{|a| a['id'] }.uniq.each do |menu_id|%>
          <% 
            totals = daily_reporting.data.select{|a| a['id'] == menu_id } 
            total_sales = totals.map{|x| x['total']}.inject(:+)
            menu_name = totals.map{|x| x['menu_name']}.uniq.join(',')
            menu_parent_name = totals.map{|x| x['menu_parent_name']}.uniq.join(',')
            percent_count =  daily_reporting.items_count == 0 ? 0 : (totals.count.to_f / daily_reporting.items_count.to_f )*100
            percent_total =  daily_reporting.total == 0 ? 0 : (total_sales.to_f / daily_reporting.total.to_f )*100
          %> 
        <tr>
          <td><%= menu_parent_name  %><%#= get_menu_item_name(menu_id)%></td>
          <td><%= menu_name%><%#= get_menu_item_name(menu_id)%></td>
          <td class='text-right'><%= totals.count%></td>
          <td class='text-right'><%= number_to_currency(total_sales.to_f / 100.to_f, unit: @restaurant.currency_symbol )%></td>
          <td class='text-right'><%= number_to_percentage(percent_count, precision: 2) %></td>
          <td class='text-right'><%= number_to_percentage(percent_total, precision: 2) %></td>
        </tr>
        <% end %>
        
      </tbody>
      <tfoot>
        <tr class='font-weight-bold bg-dark text-light'>
          <td>Total</td>
          <td></td>
          <td class='text-right'><%= @daily_reporting.items_count%></td>
          <td class='text-right'><%= number_to_currency(@daily_reporting.total.to_f / 100.to_f, unit: @restaurant.currency_symbol )%></td>
          <td class='text-right'><%= number_to_percentage(100, precision: 0) %></td>
          <td class='text-right'><%= number_to_percentage(100, precision: 0) %></td>
        </tr>
    </tfoot>
    </table>
  </div>
</div>

app/views/manager/reporting/_datatable_by_category.html.erb
<% content_for :js do %>

<script>
$(document).ready(function() {
  $("#data-<%=by%>").dataTable({
         dom: '<"row pt-4 pb-4"<"col"l><"col"f><"col text-right"B>><"row"<"col"t>><"row"<"col justify-content-center"ip >>',
        buttons: [
            {
                extend: 'excelHtml5',
                title: '<%=daily_reporting.date.strftime("%Y_%B_%d_zreport_by_#{by}_emenunow")%>'
            },
            {
                extend: 'csvHtml5',
                title: '<%=daily_reporting.date.strftime("%Y_%B_%d_zreport_by_#{by}_emenunow")%>'
            }
        ]
  });
});

</script>

<% end %>

<div class='row bg-dark text-light'>
  <div class='col pt-1'>
    <h2>Sales By <%= by.camelcase %> on <%= daily_reporting.date.strftime('%d %B %Y') %></h2>
  </div>
  <div class='col text-right pt-2'>
   <%= link_to 'Back to Daily Reports', manager_restaurant_reporting_daily_path(@restaurant), class: 'btn btn-primary btn-sm' %>
  </div>
</div>

<div class='row'>
  <div class='col'>
    <table class='table table-striped' id='data-<%=by%>'>
      <thead>
        <tr>
          <th>Section</th>
          <th class='text-right'>Count</th>
          <th class='text-right'>Total</th>
          <th class='text-right'>Percentage Items</th>
          <th class='text-right'>Percentage Sales</th>
        </tr>
      </thead>
      <tbody>
        <% daily_reporting.data.map{|a| a['menu_parent_name'] }.uniq.each do |menu_id|%>
        
          <% 
            totals = daily_reporting.data.select{|a| a['menu_parent_name'] == menu_id } 
            total_sales = totals.map{|x| x['total']}.inject(:+)
            menu_name = totals.map{|x| x['menu_name']}.uniq.join(',')
            menu_parent_name = totals.map{|x| x['menu_parent_name']}.uniq.join(',')
            percent_count =  daily_reporting.items_count == 0 ? 0 : (totals.count.to_f / daily_reporting.items_count.to_f )*100
            percent_total =  daily_reporting.total == 0 ? 0 : (total_sales.to_f / daily_reporting.total.to_f )*100
          %> 
        <tr>
          <td><%= menu_parent_name  %><%#= get_menu_item_name(menu_id)%></td>
          <td class='text-right'><%= totals.count%></td>
          <td class='text-right'><%= number_to_currency(total_sales.to_f / 100.to_f, unit: @restaurant.currency_symbol )%></td>
          <td class='text-right'><%= number_to_percentage(percent_count, precision: 2) %></td>
          <td class='text-right'><%= number_to_percentage(percent_total, precision: 2) %></td>
        </tr>
        <% end %>
        
      </tbody>
      <tfoot>
        <tr class='font-weight-bold bg-dark text-light'>
          <td>Total</td>
          <td class='text-right'><%= @daily_reporting.items_count%></td>
          <td class='text-right'><%= number_to_currency(@daily_reporting.total.to_f / 100.to_f, unit: @restaurant.currency_symbol )%></td>
          <td class='text-right'><%= number_to_percentage(100, precision: 0) %></td>
          <td class='text-right'><%= number_to_percentage(100, precision: 0) %></td>
        </tr>
    </tfoot>
    </table>
  </div>
</div>

app/views/manager/reporting/daily.html.erb
<% content_for :js do %>

<script>

$('.input-daterange').datepicker({
    format: "yyyy-mm-dd",
    todayBtn: "linked",
    autoclose: true,
    todayHighlight: true
});



$(document).ready(function() {
  $("#items-data").dataTable({
     "order": [[ 0, "desc" ]]
  });
});

</script>

<% end %>
  
  
  <main role="main" class="container">
    <div class='row'>
      <div class='col'>

          <h1>Daily Reports</h1>



      </div>
    </div>

<!-- 
<%= form_tag manager_restaurant_reporting_daily_path(@restaurant) do %>
<div class="row bg-dark text-light p-3">
  <div class="col">
    <div class="row">
      <div class="col">
        <div class="input-daterange input-group mb-2">
          <%= text_field_tag :start_date, @start_date, id: "start" , class: 'form-control', name: "start_date",  placeholder: "Start Date"  %>      
          <div class="input-group-prepend">
            <div class="input-group-text">to</div>
          </div>
          <%= text_field_tag :end_date, @end_date, id: "end" , class: 'form-control', name: "end_date",  placeholder: "End Date"  %>      
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col">
        <%= submit_tag "Update", class: 'btn btn-primary btn-block btn-sm'%>
      </div>
    </div>
  </div>
</div>
<% end %>
-->       

    <div class='row'>
      <div class='col'>

        <table class='table table-striped' id='items-data'>
          <thead>
            <tr>
              <th>Date</th>
              <th class='text-right'>Total</th>
              <th class='text-right'>Number of Items Sold</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @daily_reportings.each do |daily_reporting| %>
            <tr>
              <td><%= daily_reporting.date %></td>
              <td class='text-right'><%= number_to_currency(daily_reporting.total.to_f / 100.to_f, unit: @restaurant.currency_symbol )%></td>
              <td class='text-right'><%= daily_reporting.items_count%></td>
              <td class='text-right'><%= link_to 'View',  manager_restaurant_zreport_path(@restaurant,  daily_reporting) %></td>
            </tr>
            <% end %>
          </tbody>

        </table>    



      </div>
    </div>







</main>

app/views/manager/reporting/zreport_show.html.erb
<main role="main" class="container">
  <div class='row pt-3'>
    <div class='col'>
        <h1>Z Report</h1>
        <% if @daily_reporting.date == DateTime.current.to_date %><h6>Updates every hour on the hour</h6><% end %>
    </div>
  </div>
<div class='row mb-4'>
  <div class='col'>
    <%= render 'manager/reporting/datatable_by_category', daily_reporting: @daily_reporting, by: 'category' %>
  </div>
</div>


<div class='row bg-light text-light pb-4 '>
  <div class='col p-0 m-0 bg-info'>
  &nbsp;
  </div>

</div>


<div class='row mb-4'>
  <div class='col'>
    <%= render 'manager/reporting/datatable', daily_reporting: @daily_reporting, by: 'item' %>
  </div>
</div>


</main>