config/routes.rb
Rails.application.routes.draw do
  devise_for :patrons, controllers: {
    sessions: 'patrons/sessions',
    registrations: 'patrons/registrations'
  }
  resources :raspberry_pi_statuses
  resources :raspberry_pi_updates do
    collection do
      get :latest
      get :version
      get :files
    end
  end

  resources :stripe_webhooks, :path => "stripe-webhooks", :only => [] do
    collection do
      post :webhook, path: ""
    end
  end

  # namespace :manager do
  #   resources :printers
  # end
  resources :item_screen_types 
  
  resources :orders, :only => [:index, :show]
  resources :restaurants, :only => [:show], :path => "" do
    member do
      get :order
      get :welcome
      resources :checkouts, only: [:index, :create] do
        collection do
          get :pay
          post :pay
          post :stripe
          resources :receipt, only: [], param: :uuid do
            member do
              get :show, to: "checkouts#receipt"
            end
          end
        end
      end
    end
  end

  resources :patrons, :module => :patrons, :only => [:index, :show] do
    collection do
      get :settings, :to => "patrons#show"
      resources :orders, :only => [:index]
      resources :patron_allergens, :only => [:update]
      resources :patron_marketing_preferences, :only => [:update]
    end
  end

  resources :receipts do 
    post 'is_ready'
    post 'is_item_ready/:screen_item_id', to: 'receipts#is_item_ready', as: :screen_item_ready
    post 'is_items_ready/:receipt_id/item_screen_type_key/:item_screen_type_key', to: 'receipts#is_items_ready', as: :screen_items_ready
    post 'item_creation_broadcast'
    post 'creation_broadcast'
    collection do 
      get 'view_receipt/:uuid', to: 'receipts#view_receipt', as: :view_receipt
    end
  end
  namespace :restaurant do
    get 'list' => "home#index"
    get 'booking/:slug' => "booking#index", as: :booking
    get 'menu/:slug' => "menu#index", as: :menu

    resources :menu, :only => [:index]

  end



  resources :tables do
    post 'add_item/:menu_id' => 'tables#add_item', as: :add_item
    get 'pay'
    post 'stripe'
    get 'finish'
    get 'manager_finish'
    # get 'sectioned_menus'
    get 'sectioned_menus/:menu_id' => 'tables#show', as: 'sectioned_menus_choice'

  end
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  namespace :api do
    namespace :v1 do
      get 'menu/:id' => 'menu#index'
      get 'menu_item/:id', to: 'menu#menu_item'
      get 'menu_optionals', to: 'menu#menu_optionals'
      get 'menu_optionals/:items', to: 'menu#menu_optionals'
    end
  end
  namespace :manager do
    resources :restaurants, :param => :restaurant_id do
      member do
        resources :discount_codes
        resources :orders, :only => [] do
          member do
            resources :refunds, only: [:create]
          end
        end
      end
      collection do
        resources :administrations, :only => [:index] do
          member do
            get :login_as
          end
        end
        resources :reports, :only => [:index]
      end
    end
    resources :home do
      collection do
        get :dashboard
        get :menu
      end
    end

    get 'live_tables/:restaurant_id' => 'live#tables', as: :live_tables
    get 'live_items/:restaurant_id' => 'live#items', as: :live_items
    get 'live_orders/:restaurant_id' => 'live#orders', as: :live_orders
    get 'live_orders/broadcast/:restaurant_id' => 'live#orders_broadcast', as: :live_orders_broadcast
    get 'live_food/:restaurant_id' => 'live#food', as: :live_food
    get 'live_food/broadcast/:restaurant_id' => 'live#orders_broadcast', as: :live_food_broadcast
    get 'live_drinks/:restaurant_id' => 'live#drinks', as: :live_drinks
    get 'live_drinks/broadcast/:restaurant_id' => 'live#orders_broadcast', as: :live_drinks_broadcast
    get 'receipts/:restaurant_id' => 'live#receipts', as: :receipts
    get 'send_receipt/:receipt_id' => 'live#send_receipt', as: :send_receipts
    get 'service/:restaurant_id/item/:table_item_id' => 'live#service', as: :live_service
    get 'ready/:restaurant_id/item/:table_item_id' => 'live#ready', as: :live_ready


    resources :features
    resources :templates  
    resources :settings
    resources :packages do
      post 'add_feature/:feature_id', action: :add_feature, as: :add_feature
      post 'remove_feature/:feature_id', action: :remove_feature, as: :remove_feature
    end

    resources :cuisines
    resources :restaurants do

      post 'set_delay'
      post 'reporting/daily'
      get 'reporting/daily'
      get 'reporting/zreport_show/:daily_reporting_id', to: 'reporting#zreport_show', as: :zreport

      resources :opening_times
      resources :delivery_postcodes

      resources :themes

      resources :item_screens

      resources :pi_interfaces do 
        get :request_lsusb
        resources :printers 
      end
      post 'add_feature/:feature_id', action: :add_feature, as: :add_feature
      post 'remove_feature/:feature_id', action: :remove_feature, as: :remove_feature
      post 'toggle_feature/:feature_id', action: :toggle_feature, as: :toggle_feature
      get 'active', action: :active
      post 'toggle_active', action: :toggle_active
      post 'add_template', action: :add_template


      resources :menus do
        post :clone
      end
      resources :restaurant_tables do
        collection do
          get :qr
        end
      end
      resources :custom_lists do 
        resources :custom_list_items
        post :up
        post :down
      end
    end
    devise_for :restaurant_users, path: 'manager', controllers: {
      sessions: 'manager/restaurant_users/sessions',
      registrations: 'manager/restaurant_users/registrations',
      passwords: 'manager/restaurant_users/passwords'
    }
  end

  namespace :onboarding do
    resources :restaurants do
      get 'services'
      get 'connect'
      get 'complete'
      post 'toggle_feature/:feature_id', action: :toggle_feature, as: :toggle_feature
      post 'dashboard_login', action: :dashboard_login, as: :dashboard_login
    end
    
    get 'start', to: 'home#start'
    get 'continue', to: 'home#continue'
    patch 'agree', to: 'home#tos_agree'

    devise_for :restaurant_users, path: '/', controllers: {
      sessions: 'onboarding/restaurant_users/sessions',
      registrations: 'onboarding/restaurant_users/registrations',
      passwords: 'onboarding/restaurant_users/passwords'
    }
  end

#printing

get 'receipt/:receipt_id/print/:printer_id', to: 'manager/printers#print', as: :print_receipt
get 'receipt/:receipt_id/screen_item_uuid/:uuid/print/:printer_id', to: 'manager/printers#print_item', as: :print_item_receipt
get 'receipt/:receipt_id/key/:item_screen_type_key/print/:printer_id', to: 'manager/printers#print_items', as: :print_items_receipt


  # get 'order/remove_from_basket/:path/:uuid', to: 'order#remove_from_basket', as: :remove_from_basket
  # get 'order/receipt/:path/:uuid', to: 'order#receipt', as: :order_receipt
  # get 'order/checkout/:path', to: 'order#checkout', as: :checkout
  # post 'order/pay/:path', to: 'order#pay', as: :pay
  # get 'order/checkoutx/:path', to: 'order#checkoutx', as: :checkoutx
  # post 'order/stripe/:path', to: 'order#stripe', as: :stripe
  # get 'order/add_to_basket/:path', to: 'order#add_to_basket', as: :add_to_basket_base
  # get 'order/add_to_basket', to: 'baskets#index', as: :add_to_basket
  get 'baskets/:path/menu/:menu_id/section/:section_id', to: 'baskets#index', as: :order_menu_section
  # get 'order/:path/menu/:menu_id', to: 'restaurants#index', as: :order_menu
  get 'order/:path', to: 'order#index'

  resources :baskets, :only => [:update], param: :path

  get 'home_mobile/index'
  get 'home/index'
  post 'home/register_table'
  get 'home/register_table/:code' => 'home#register_table', as: :register_table
  post 'home/start_table/:table_id' => 'home#start_table', via: %i[get post], as: :start_table
  get 'home/table'
  post 'home/set_locale/:language_id' => 'home#set_locale', as: :home_set_locale

  get '/:name', to: 'restaurant/menu#index'

  root 'home#index'
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  # layout 'order'

  def index
    @restaurants = Restaurant.all
  end

  def register_table
    @code = params[:code].upcase
    @restaurant_table = RestaurantTable.find_by(code: @code)
    table_id = cookies[:table_id]
    @table = Table.find_by(id: table_id, restaurant_table_id: @restaurant_table.id, aasm_state: :started) if table_id && @restaurant_table
    respond_to do |format|
      if @table.present?

     
          format.html { redirect_to table_path(@table.id), notice: t('messages.table_joined_successfully') }
     
      else
        format.html
      end
    end
  end

 

  def set_locale
    language = Language.find(params[:language_id])
    cookies[:locale] = language.locale
    cookies[:language] = language.name
    redirect_back(fallback_location: home_index_path)
  end

  def start_table
    table_id = params[:table_id]
    @restaurant_table = RestaurantTable.find(table_id)
    password = params[:password].downcase
    live_table = @restaurant_table.tables.where(aasm_state: :started)
    if live_table.blank?
      @table = Table.create(
        restaurant_table_id: @restaurant_table.id,
        password: password
      )
      cookies[:restaurant_table_id] = { value: @restaurant_table.id, expires: 4.hour.from_now }
      cookies[:table_id] = { value: @table.id, expires: 4.hour.from_now }
    else
      @table = live_table.find_by(password: password)
      if @table.present?
        cookies[:restaurant_table_id] = { value: @restaurant_table.id, expires: 4.hour.from_now }
        cookies[:table_id] = { value: @table.id, expires: 4.hour.from_now }
      end
    end
    respond_to do |format|
      if @table.present?

        # binding.pry


          format.html { redirect_to table_path(@table.id), notice: t('messages.table_created_successfully') }

      else
        format.html { redirect_to register_table_path(@restaurant_table.code), alert: t('messages.table_incorrect_password') }
      end
    end
  end
end

app/controllers/manager/home_controller.rb
# frozen_string_literal: true

module Manager
  class HomeController < Manager::BaseController
    before_action :authenticate_manager_restaurant_user!, except: [:index]

    def index
      @restaurant = current_manager_restaurant_user.restaurant if current_manager_restaurant_user
    end

    def menu
      @restaurant = current_manager_restaurant_user.restaurant
    end

    def dashboard
      @restaurant = current_manager_restaurant_user.restaurant
    end
  end
end

app/controllers/onboarding/home_controller.rb
# frozen_string_literal: true

module Onboarding
  class HomeController < Onboarding::BaseController
    before_action :authenticate_onboarding_restaurant_user!, except: [:start]
    before_action :get_restaurant, except: [:start]
    before_action :get_onboarding
    before_action :get_features
    before_action :set_progress

    def start
      @restaurant = current_onboarding_restaurant_user.restaurant if current_onboarding_restaurant_user
      @progress[:register] += ' current'
    end
    
    def continue
      if @onboard&.completed
        redirect_to onboarding_restaurant_complete_path(@restaurant)
      elsif current_onboarding_restaurant_user.onboard&.tos_agreed? && @restaurant
        # @progress[:terms] = 'complete'
        # @progress[:restaurant] = 'complete'
        redirect_to edit_onboarding_restaurant_path(@restaurant)
      elsif current_onboarding_restaurant_user.onboard&.tos_agreed?
        # @progress[:terms] += 'complete'
        redirect_to new_onboarding_restaurant_path(@restaurant)
      elsif !current_onboarding_restaurant_user.onboard
        # @progress[:terms] += 'current'
        new_onboarding
      end
      @progress[:terms] += ' current'
    end
    
    def tos_agree
      respond_to do |format|
        if @onboard.update(onboard_params) && @restaurant
          tos_agreement
          format.html { redirect_to onboarding_restaurant_services_path(@restaurant), notice: 'Terms of service agreed.' }
          format.json { render :continue, status: :ok, location: @onboard }
        elsif @onboard.update(onboard_params)
          tos_agreement
          format.html { redirect_to new_onboarding_restaurant_path(@restaurant), notice: 'Terms of service agreed.' }
          format.json { render :continue, status: :ok, location: @onboard }
        else
          format.html { render :continue }
          format.json { render json: @onboard.errors, status: :unprocessable_entity }
        end
      end
    end
    
    private
    
    def get_restaurant
      @restaurant = current_onboarding_restaurant_user.restaurant
    end
    
    def get_onboarding
      @onboard = current_onboarding_restaurant_user.onboard if current_onboarding_restaurant_user&.onboard.present?
    end
    
    def new_onboarding
      @onboard = Onboard.new
      @onboard.update_attribute(:restaurant_user_id, current_onboarding_restaurant_user.id)
    end
    
    def tos_agreement
      @onboard.update_attribute(:tos_agreed_date, DateTime.now)
      @onboard.update_attribute(:tos_ip, request.ip)
      @onboard.update_attribute(:tos_user_agent, request.user_agent)
    end
        
    def get_features
      @features = Feature.all
      @services = Feature.find([12,9,11,10])
    end
    
    def set_progress
      @progress = {}
      @progress[:register] = current_onboarding_restaurant_user ? 'complete' : ''
      @progress[:terms] = current_onboarding_restaurant_user&.onboard&.tos_agreed? ? 'complete' : ''
      @progress[:restaurant] = current_onboarding_restaurant_user&.restaurant ? 'complete' : ''
      @progress[:services] = (current_onboarding_restaurant_user&.restaurant && (current_onboarding_restaurant_user.restaurant.features & Feature.find([12,9,11,10])).any?) ? 'complete' : ''
      @progress[:connect] = @onboard&.completed ? 'complete' : @onboard&.completed.nil? ? '' : 'failed'
    end

    def onboard_params
      params.require(:onboard).permit(:tos_agreed, :tos_agreed_date, :tos_ver_agreed, :tos_ip, :tos_user_agent, :free_trial, :completed)
    end

  end
end

app/controllers/restaurant/home_controller.rb
class Restaurant::HomeController < ApplicationController
  def index

    redirect_to root_path
  	# @restaurants = Restaurant.all



  end
  def show


  	name = params[:name]
  	@restaurant = Restaurant.find(name)



  end
end

app/views/home/_menu.html.erb
  	<div class="container pt-3">
  <div class="shadow-lg p-3 mb-5 bg-white rounded">
<h1 class="fs-max text-center"><%= menu.name%></h1>
<% menu.children.each do |level1|%>
  <div class="row">
    <div class="col">
    		<%= render "home/#{level1.node_type}", menu: level1, level: 1%>
      	<% level1.children.each do |level2| %>
      		  <div class="row">
					    <div class="col ml-2">
					      	<%= render "home/#{level2.node_type}", menu: level2, level: 2%>

						      	<% level2.children.each do |level3| %>
					      		
					      		  <div class="row">

										    <div class="col ml-3">
										      	<%= render "home/#{level3.node_type}", menu: level3, level: 3%>
											      	<% level3.children.each do |level4| %>
										      		

											      		  <div class="row">

																    <div class="col ml-4">
																      	<%= render "home/#{level4.node_type}", menu: level4, level: 4%>
																	      	<% level4.children.each do |level5| %>
																      		


																      			      		  <div class="row">
																											    <div class="col ml-5">
																											      	<%= render "home/#{level5.node_type}", menu: level5, level: 5%>
																												      	<% level5.children.each do |level6| %>
																											      		

																												      	      		  <div class="row">
																																						    <div class="col">
																																						      	<%= render "home/#{level6.node_type}", menu: level6, level: 6%>
																																							      	<% level6.children.each do |level7| %>
																																						      		

																																							      		  <div class="row">
																																												    <div class="col">
																																												      	<%= render "home/#{level7.node_type}", menu: level7, level: 7%>
																																													      	<% level7.children.each do |level8| %>
																																												      		
																																													      			 <%= render "home/#{level8.node_type}", menu: level8, level: 8%>
																																												      		<% end %>
																																												    </div>
																																												  </div>




																																						      		<% end %>
																																						    </div>
																																						  </div>



																											      		<% end %>
																											    </div>
																											  </div>


																      		<% end %>
																    </div>
																  </div>




										      		<% end %>
										    </div>
										  </div>



					      		<% end %>
					    </div>
					  </div>


      	<% end %>
    </div>
  </div>
 <% end %>
  
  </div>
	</div>

app/views/home/index.html.erb
<% content_for :hero do %>
<div class="jumbotron jumbotron-fluid hero-main-user-background mb-0">
	<div class="container text-light">
		<div class="row mb-0">
			<div class="col-lg-12 pt-3 pb-3">
				<h1 class="display-2"><%= t('furniture.start_eating') %></h1>
			</div>
		</div>
		<div class="row mb-0">
			<div class="col-lg-12 pt-3 pb-3">
				<h3><%= t('furniture.enter_table_code')%></h3>
			</div>
		</div>
		<div class="mb-0">
			<div class="pt-3 pb-3 mx-auto">
				<%= form_tag home_register_table_path do %>
				<%= text_field_tag :code, nil, :class=>"p-3" %>
				<%= submit_tag t('furniture.enter_table_code_submit'), class: 'btn btn-warning btn-sm mb-1 p-3'%>
				<% end %>
			</div>
		</div>
	</div>
</div>
<% end %>

<main role="main" class="container">
	<div class="row">
		<div class="col-lg-12 my-0 py-5 pb-3">
			<h2><%= t('furniture.where_to_eat')%></h2>
			<!-- <p><%= t('furniture.available_restaurants')%></p> -->
			<div class="row">
				<div class="col-lg-12 my-0 py-5 pb-3">
					<ul>
						<% @restaurants.select{|x|x.show_on_homepage && x.path.present?}.each do |restaurant| %>
							<li class="h5"><%= link_to restaurant.name, welcome_restaurant_path(restaurant.path), class: 'text-primary' %></li>
						<% end %>
					</ul>
				</div>
			</div>
		</div>
	</div>
</main>

app/views/home/register_table.html.erb
<% content_for(:hero) do %>
<div class="container-fluid px-0">
	<% if @restaurant_table %>
    <% if @restaurant_table.tables.where(aasm_state: :started).count == 0%>
      <div class="jumbotron jumbotron-fluid hero-main-background2 mb-0  text-light">
        <div class="container  text-center">
          <h2 class="display-2"><%= t('register_table.start.message')%></h2>
          <p class="">
            <h2><%= t('register_table.start.password_message')%></h2>
            <%= form_tag start_table_path(@restaurant_table) do %>
              <%= text_field_tag :password %>
              <%= submit_tag t('register_table.start.password_submit'), class: 'btn btn-primary btn-sm  mb-1'%>
            <% end %>
            <p><i><%= t('register_table.start.password_help')%></i></p>
          </p>
        </div>
      </div>
    <% else %>
      <div class="jumbotron jumbotron-fluid hero-main-background2 mb-0 text-light">
        <div class="container text-center">
          <h2 class="display-2 pb-4"><%= t('register_table.join.message')%></h2>
          <p class="">
            <h2><%= t('register_table.join.password_message')%></h2>
            <%= form_tag start_table_path(@restaurant_table) do %>
              <%= text_field_tag :password, nil, :class=>"p-3" %>
              <%= submit_tag t('register_table.join.password_submit'), class: 'btn btn-primary btn-sm mb-1 p-3'%>
            <% end %>
          </p>
        </div>
      </div>
    <% end %>
  <% else %>  
    <div class="jumbotron jumbotron-fluid hero-main-background2 mb-0 text-light">
      <div class="container  text-center">
        <h2 class="display-4 "><%= t('register_table.error.message')%></h2>
        <%= link_to t('register_table.error.home_button'), home_index_path, class: 'btn btn-warning'%>
      </div>
    </div>
  <% end %>
</div>
<% end %>
<% if @restaurant_table %>
  <div class="row py-5">
    <div class="col-sm pl-4 mt-4">
      <h3><strong><%= t('register_table.details.title')%>:</strong></h3>
      <table class="table">
        <thead>
          <tr>
            <th><%= t('register_table.details.headers.name')%></th>
            <th><%= t('register_table.details.headers.code')%></th>
            <th><%= t('register_table.details.headers.number')%></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @restaurant_table.restaurant_name%></td>
            <td><code><%= @restaurant_table.code%></code></td>
            <td><%= @restaurant_table.number %></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
<% end %>

app/views/home/restaurant_user_authenticated.html.erb
<main role="main" class="container">
  <div class="my-3 p-3 bg-white rounded shadow-sm">
    <h6 class="border-bottom border-gray pb-2 mb-0">Dashboard</h6>
    <div class="media text-muted pt-3">
      <img data-src="holder.js/32x32?theme=thumb&bg=007bff&fg=007bff&size=1" alt="" class="mr-2 rounded">
      <div class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
        <div class="d-flex justify-content-between align-items-center w-100">
          <strong class="text-gray-dark">Restaurant</strong>
          <% if @restaurant.present? %>
            <%= link_to("Manage Restaurant", restaurant_path(@restaurant.id))%>
          <% else %>
            <%= link_to("Add Restaurant", new_restaurant_path)%>
          <% end %>
        </div>
        <span class="d-block"><%= @restaurant.name if @restaurant%></span>
      </div>
    </div>
    <div class="media text-muted pt-3">
      <img data-src="holder.js/32x32?theme=thumb&bg=007bff&fg=007bff&size=1" alt="" class="mr-2 rounded">
      <div class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
        <div class="d-flex justify-content-between align-items-center w-100">
          <strong class="text-gray-dark">Menus</strong>
          <%= link_to("Manage Menus", restaurant_menus_path(@restaurant), class: "nav-link") if @restaurant %>
        </div>
        
        <% @restaurant.menus.roots.each do |menu| %>
          <%= render 'home/menu', menu: menu%>
        <% end if @restaurant %>
      </div>
    </div>
<!--     <div class="media text-muted pt-3">
      <img data-src="holder.js/32x32?theme=thumb&bg=007bff&fg=007bff&size=1" alt="" class="mr-2 rounded">
      <div class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
        <div class="d-flex justify-content-between align-items-center w-100">
          <strong class="text-gray-dark">Galleries</strong>
          <a href="#">Manage Galleries</a>
        </div>
        <span class="d-block">Pics Pics</span>
      </div>
    </div>
  -->   
  </div>
</main>

app/views/home/resturant_user_index.html.erb
    <main role="main">

      <!-- Main jumbotron for a primary marketing message or call to action -->
      <div class="jumbotron jumbotron-fluid hero-main-background">
        <div class="container">
          <h2 class="display-1 text-center text-dark">Resturant Menus</h2>
          <h1 class="display-3 text-center text-dark">Re-Imagined</h1>
          <p class=" text-center ">

          <% if current_resturant_user %>

            <%= link_to "Manage Resturant", home_resturant_user_authenticated_path, class: 'btn btn-primary btn-lg', role: 'button'%>

          <% else %>

            <%= link_to "Log In", new_resturant_user_session_path, class: 'btn btn-primary btn-lg', role: 'button'%>
           <%= link_to "Sign Up", new_resturant_user_registration_path, class: 'btn btn-secondary btn-lg', role: 'button'%>
          
          <% end %>

          </p>
        </div>
      </div>

      <div class="container">
        <!-- Example row of columns -->
        <div class="row">
          <div class="col-md-4">
            <h2>Put your menu online</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
          </div>
          <div class="col-md-4">
            <h2>Heading</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
          </div>
          <div class="col-md-4">
            <h2>Heading</h2>
            <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
            <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
          </div>
        </div>

        <hr>

      </div> <!-- /container -->

    </main>

app/views/home/user_index.html.erb
    <main role="main">

      <!-- Main jumbotron for a primary marketing message or call to action -->
      <div class="jumbotron jumbotron-fluid hero-main-background">
        <div class="container">
          <h2 class="display-1 text-center text-dark">Restaurant Menus</h2>
          <h1 class="display-3 text-center text-dark">Re-Imagined</h1>
          <p class=" text-center ">
            <a class="btn btn-primary btn-lg" href="#" role="button">Sign Up</a>
            <a class="btn btn-lg btn-secondary" href="#" role="button">Log In</a>
          </p>
        </div>
      </div>

      <div class="container">
        <!-- Example row of columns -->
        <div class="row">
          <div class="col-md-4">
            <h2>Your eating Profile</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
          </div>
          <div class="col-md-4">
            <h2>Heading</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
          </div>
          <div class="col-md-4">
            <h2>Heading</h2>
            <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
            <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
          </div>
        </div>

        <hr>

      </div> <!-- /container -->

    </main>