config/routes.rb
Rails.application.routes.draw do
  devise_for :patrons, controllers: {
    sessions: 'patrons/sessions',
    registrations: 'patrons/registrations'
  }
  resources :raspberry_pi_statuses
  resources :raspberry_pi_updates do
    collection do
      get :latest
      get :version
      get :files
    end
  end

  resources :stripe_webhooks, :path => "stripe-webhooks", :only => [] do
    collection do
      post :webhook, path: ""
    end
  end

  # namespace :manager do
  #   resources :printers
  # end
  resources :item_screen_types 
  
  resources :orders, :only => [:index, :show]
  resources :restaurants, :only => [:show], :path => "" do
    member do
      get :order
      get :welcome
      resources :checkouts, only: [:index, :create] do
        collection do
          get :pay
          post :pay
          post :stripe
          resources :receipt, only: [], param: :uuid do
            member do
              get :show, to: "checkouts#receipt"
            end
          end
        end
      end
    end
  end

  resources :patrons, :module => :patrons, :only => [:index, :show] do
    collection do
      get :settings, :to => "patrons#show"
      resources :orders, :only => [:index]
      resources :patron_allergens, :only => [:update]
      resources :patron_marketing_preferences, :only => [:update]
    end
  end

  resources :receipts do 
    post 'is_ready'
    post 'is_item_ready/:screen_item_id', to: 'receipts#is_item_ready', as: :screen_item_ready
    post 'is_items_ready/:receipt_id/item_screen_type_key/:item_screen_type_key', to: 'receipts#is_items_ready', as: :screen_items_ready
    post 'item_creation_broadcast'
    post 'creation_broadcast'
    collection do 
      get 'view_receipt/:uuid', to: 'receipts#view_receipt', as: :view_receipt
    end
  end
  namespace :restaurant do
    get 'list' => "home#index"
    get 'booking/:slug' => "booking#index", as: :booking
    get 'menu/:slug' => "menu#index", as: :menu

    resources :menu, :only => [:index]

  end



  resources :tables do
    post 'add_item/:menu_id' => 'tables#add_item', as: :add_item
    get 'pay'
    post 'stripe'
    get 'finish'
    get 'manager_finish'
    # get 'sectioned_menus'
    get 'sectioned_menus/:menu_id' => 'tables#show', as: 'sectioned_menus_choice'

  end
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  namespace :api do
    namespace :v1 do
      get 'menu/:id' => 'menu#index'
      get 'menu_item/:id', to: 'menu#menu_item'
      get 'menu_optionals', to: 'menu#menu_optionals'
      get 'menu_optionals/:items', to: 'menu#menu_optionals'
    end
  end
  namespace :manager do
    resources :restaurants, :param => :restaurant_id do
      member do
        resources :discount_codes
        resources :orders, :only => [] do
          member do
            resources :refunds, only: [:create]
          end
        end
      end
      collection do
        resources :administrations, :only => [:index] do
          member do
            get :login_as
          end
        end
        resources :reports, :only => [:index]
      end
    end
    resources :home do
      collection do
        get :dashboard
        get :menu
      end
    end

    get 'live_tables/:restaurant_id' => 'live#tables', as: :live_tables
    get 'live_items/:restaurant_id' => 'live#items', as: :live_items
    get 'live_orders/:restaurant_id' => 'live#orders', as: :live_orders
    get 'live_orders/broadcast/:restaurant_id' => 'live#orders_broadcast', as: :live_orders_broadcast
    get 'live_food/:restaurant_id' => 'live#food', as: :live_food
    get 'live_food/broadcast/:restaurant_id' => 'live#orders_broadcast', as: :live_food_broadcast
    get 'live_drinks/:restaurant_id' => 'live#drinks', as: :live_drinks
    get 'live_drinks/broadcast/:restaurant_id' => 'live#orders_broadcast', as: :live_drinks_broadcast
    get 'receipts/:restaurant_id' => 'live#receipts', as: :receipts
    get 'send_receipt/:receipt_id' => 'live#send_receipt', as: :send_receipts
    get 'service/:restaurant_id/item/:table_item_id' => 'live#service', as: :live_service
    get 'ready/:restaurant_id/item/:table_item_id' => 'live#ready', as: :live_ready


    resources :features
    resources :templates  
    resources :settings
    resources :packages do
      post 'add_feature/:feature_id', action: :add_feature, as: :add_feature
      post 'remove_feature/:feature_id', action: :remove_feature, as: :remove_feature
    end

    resources :cuisines
    resources :restaurants do

      post 'set_delay'
      post 'reporting/daily'
      get 'reporting/daily'
      get 'reporting/zreport_show/:daily_reporting_id', to: 'reporting#zreport_show', as: :zreport

      resources :opening_times
      resources :delivery_postcodes

      resources :themes

      resources :item_screens

      resources :pi_interfaces do 
        get :request_lsusb
        resources :printers 
      end
      post 'add_feature/:feature_id', action: :add_feature, as: :add_feature
      post 'remove_feature/:feature_id', action: :remove_feature, as: :remove_feature
      post 'toggle_feature/:feature_id', action: :toggle_feature, as: :toggle_feature
      get 'active', action: :active
      post 'toggle_active', action: :toggle_active
      post 'add_template', action: :add_template


      resources :menus do
        post :clone
      end
      resources :restaurant_tables do
        collection do
          get :qr
        end
      end
      resources :custom_lists do 
        resources :custom_list_items
        post :up
        post :down
      end
    end
    devise_for :restaurant_users, path: 'manager', controllers: {
      sessions: 'manager/restaurant_users/sessions',
      registrations: 'manager/restaurant_users/registrations',
      passwords: 'manager/restaurant_users/passwords'
    }
  end

  namespace :onboarding do
    resources :restaurants do
      get 'services'
      get 'connect'
      get 'complete'
      post 'toggle_feature/:feature_id', action: :toggle_feature, as: :toggle_feature
      post 'dashboard_login', action: :dashboard_login, as: :dashboard_login
    end
    
    get 'start', to: 'home#start'
    get 'continue', to: 'home#continue'
    patch 'agree', to: 'home#tos_agree'

    devise_for :restaurant_users, path: '/', controllers: {
      sessions: 'onboarding/restaurant_users/sessions',
      registrations: 'onboarding/restaurant_users/registrations',
      passwords: 'onboarding/restaurant_users/passwords'
    }
  end

#printing

get 'receipt/:receipt_id/print/:printer_id', to: 'manager/printers#print', as: :print_receipt
get 'receipt/:receipt_id/screen_item_uuid/:uuid/print/:printer_id', to: 'manager/printers#print_item', as: :print_item_receipt
get 'receipt/:receipt_id/key/:item_screen_type_key/print/:printer_id', to: 'manager/printers#print_items', as: :print_items_receipt


  # get 'order/remove_from_basket/:path/:uuid', to: 'order#remove_from_basket', as: :remove_from_basket
  # get 'order/receipt/:path/:uuid', to: 'order#receipt', as: :order_receipt
  # get 'order/checkout/:path', to: 'order#checkout', as: :checkout
  # post 'order/pay/:path', to: 'order#pay', as: :pay
  # get 'order/checkoutx/:path', to: 'order#checkoutx', as: :checkoutx
  # post 'order/stripe/:path', to: 'order#stripe', as: :stripe
  # get 'order/add_to_basket/:path', to: 'order#add_to_basket', as: :add_to_basket_base
  # get 'order/add_to_basket', to: 'baskets#index', as: :add_to_basket
  get 'baskets/:path/menu/:menu_id/section/:section_id', to: 'baskets#index', as: :order_menu_section
  # get 'order/:path/menu/:menu_id', to: 'restaurants#index', as: :order_menu
  get 'order/:path', to: 'order#index'

  resources :baskets, :only => [:update], param: :path

  get 'home_mobile/index'
  get 'home/index'
  post 'home/register_table'
  get 'home/register_table/:code' => 'home#register_table', as: :register_table
  post 'home/start_table/:table_id' => 'home#start_table', via: %i[get post], as: :start_table
  get 'home/table'
  post 'home/set_locale/:language_id' => 'home#set_locale', as: :home_set_locale

  get '/:name', to: 'restaurant/menu#index'

  root 'home#index'
end

app/models/manager.rb
module Manager
  def self.table_name_prefix
    'manager_'
  end
end

app/controllers/manager/administrations_controller.rb
# frozen_string_literal: true

module Manager
  class AdministrationsController < Manager::BaseController
    before_action :authenticate_manager_restaurant_user!
    before_action :authenticate_admin!

    def index
      @restaurants = Restaurant.includes(:restaurant_user).all
    end

    def login_as
      @restaurant_user = RestaurantUser.find(params[:id])
      sign_in(@restaurant_user)
      redirect_to root_path, notice: "Force signed in successfully"
    end

    private

  end
end

app/controllers/manager/base_controller.rb
# frozen_string_literal: true

module Manager
  class BaseController < ApplicationController
	  alias_method :current_user, :current_manager_restaurant_user # Could be :current_member or :logged_in_user

    layout 'manager'

    rescue_from CanCan::AccessDenied do |exception|
      redirect_to manager_home_index_path, notice: exception.message 
    end


    def set_restaurant
      @restaurant = Restaurant.where(id: params[:restaurant_id]).first || current_manager_restaurant_user.restaurant
      unless current_manager_restaurant_user.id == @restaurant.restaurant_user_id
        redirect_to '/422.html'
      end
    end

    def authenticate_admin!
      current_user.admin ? true : (redirect_to manager_home_index_path, :notice => "Admin level required")
    end
  end

end

app/controllers/manager/custom_list_items_controller.rb
# frozen_string_literal: true

module Manager

class CustomListItemsController < Manager::BaseController
  before_action :authenticate_manager_restaurant_user!
  before_action :set_custom_list_item, only: [:show, :edit, :update, :destroy]
  before_action :set_restaurant
  before_action :set_custom_list
  
  # GET /custom_list_items
  # GET /custom_list_items.json
  def index
    @custom_list_items = CustomListItem.all
  end

  # GET /custom_list_items/1
  # GET /custom_list_items/1.json
  def show
  end

  # GET /custom_list_items/new
  def new
    @custom_list_item = CustomListItem.new
  end

  # GET /custom_list_items/1/edit
  def edit
  end

  # POST /custom_list_items
  # POST /custom_list_items.json
  def create
    @custom_list_item = CustomListItem.new(custom_list_item_params)

    respond_to do |format|
      if @custom_list_item.save
        format.html { redirect_to manager_restaurant_custom_list_path(@restaurant, @custom_list), notice: 'Option Set item was successfully created.' }
        format.json { render :show, status: :created, location: @custom_list_item }
      else
        format.html { render :new }
        format.json { render json: @custom_list_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /custom_list_items/1
  # PATCH/PUT /custom_list_items/1.json
  def update
    
    Rails.cache.delete("api/restaurant/#{@restaurant.id}/menu")
    Rails.cache.delete("restaurant_order_menu_#{@restaurant.id}")

    Rails.cache.delete("custom_list_item_#{@custom_list_item.id}")
    Rails.cache.delete_matched("custom_list_items*-#{@custom_list_item.id}-*")
    Rails.cache.delete("custom_list_#{@custom_list.id}")
    
    respond_to do |format|
      if @custom_list_item.update(custom_list_item_params)
        format.html { redirect_to manager_restaurant_custom_list_path(@restaurant, @custom_list), notice: 'Option Set item was successfully updated.' }
        format.json { render :show, status: :ok, location: @custom_list_item }
      else
        format.html { render :edit }
        format.json { render json: @custom_list_item.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # DELETE /custom_list_items/1
  # DELETE /custom_list_items/1.json
  def destroy
    
    Rails.cache.delete("api/restaurant/#{@restaurant.id}/menu")
    Rails.cache.delete("restaurant_order_menu_#{@restaurant.id}")
    
    Rails.cache.delete("custom_list_item_#{@custom_list_item.id}")
    Rails.cache.delete("custom_list_#{@custom_list.id}")

    clear_list_item(@custom_list.id, @custom_list_item.id)
    @custom_list_item.destroy
    respond_to do |format|
      format.html { redirect_to manager_restaurant_custom_list_path(@restaurant, @custom_list), notice: 'Option Set item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_custom_list_item
      @custom_list_item = CustomListItem.find(params[:id])
    end

    def set_custom_list
      @custom_list = CustomList.find(params[:custom_list_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def custom_list_item_params
      params.require(:custom_list_item).permit(:name, :custom_list_id, :price, :description, :available)
    end

    def clear_list_item(list_id, list_item_id)
      query = Menu.where("custom_lists -> '#{list_id}' ? '#{list_item_id}'")
      query.each do |h|
        h.custom_lists["#{list_id}"].delete("#{list_item_id}")
        h.custom_lists.delete("#{list_id}") if h.custom_lists["#{list_id}"].length == 0
        h.save
      end
    end

  end

end

app/controllers/manager/custom_lists_controller.rb
# frozen_string_literal: true

module Manager

class CustomListsController < Manager::BaseController
  before_action :authenticate_manager_restaurant_user!
  before_action :set_custom_list, only: [:show, :edit, :update, :destroy]
  before_action :set_restaurant

  # GET /custom_lists
  # GET /custom_lists.json
  def index
    @custom_lists = CustomList.where(restaurant_id: @restaurant.id)
  end

  # GET /custom_lists/1
  # GET /custom_lists/1.json
  def show
  end

  # GET /custom_lists/new
  def new
    @custom_list = CustomList.new
    @custom_list.restaurant_id = @restaurant.id
  end

  # GET /custom_lists/1/edit
  def edit
  end

  def up
    @restaurant = Restaurant.find(params[:restaurant_id])
    @custom_list = CustomList.find(params[:custom_list_id])
    @custom_list.move_higher
    @custom_list.save
    redirect_to manager_restaurant_custom_lists_path(@restaurant)
  end

  def down
    @restaurant = Restaurant.find(params[:restaurant_id])
    @custom_list = CustomList.find(params[:custom_list_id])
    @custom_list.move_lower
    @custom_list.save
    redirect_to manager_restaurant_custom_lists_path(@restaurant)
  end

  # POST /custom_lists
  # POST /custom_lists.json
  def create
    @custom_list = CustomList.new(custom_list_params)
    Rails.cache.delete("api/restaurant/#{@restaurant.id}/menu")
    Rails.cache.delete("restaurant_order_menu_#{@restaurant.id}")

    respond_to do |format|
      if @custom_list.save
        format.html { redirect_to manager_restaurant_custom_list_path(@restaurant, @custom_list), notice: 'Option Set was successfully created.' }
        format.json { render :show, status: :created, location: @custom_list }
      else
        format.html { render :new }
        format.json { render json: @custom_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /custom_lists/1
  # PATCH/PUT /custom_lists/1.json
  def update

    Rails.cache.delete("api/restaurant/#{@restaurant.id}/menu")
    Rails.cache.delete("restaurant_order_menu_#{@restaurant.id}")
    
    Rails.cache.delete("custom_list_constraint_#{@custom_list.id}")
    Rails.cache.delete("custom_list_#{@custom_list.id}")
    Rails.cache.delete("custom_list_name_#{@custom_list.id}")
    
    respond_to do |format|
      if @custom_list.update(custom_list_params)
        format.html { redirect_to manager_restaurant_custom_list_path(@restaurant, @custom_list), notice: 'Option Set was successfully updated.' }
        format.json { render :show, status: :ok, location: @custom_list }
      else
        format.html { render :edit }
        format.json { render json: @custom_list.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # DELETE /custom_lists/1
  # DELETE /custom_lists/1.json
  def destroy
    
    Rails.cache.delete("api/restaurant/#{@restaurant.id}/menu")
    Rails.cache.delete("restaurant_order_menu_#{@restaurant.id}")
    
    Rails.cache.delete("custom_list_#{@custom_list.id}")
    Rails.cache.delete("custom_list_name_#{@custom_list.id}")

    @custom_list.destroy
    respond_to do |format|
      format.html { redirect_to manager_restaurant_custom_lists_path(@restaurant), notice: 'Option Set was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_custom_list
      @custom_list = CustomList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def custom_list_params
      params.require(:custom_list).permit(:name, :restaurant_id, :constraint, :required_items, :limit_min, :limit_count, :limit_max)
    end
  end

end

app/controllers/manager/home_controller.rb
# frozen_string_literal: true

module Manager
  class HomeController < Manager::BaseController
    before_action :authenticate_manager_restaurant_user!, except: [:index]

    def index
      @restaurant = current_manager_restaurant_user.restaurant if current_manager_restaurant_user
    end

    def menu
      @restaurant = current_manager_restaurant_user.restaurant
    end

    def dashboard
      @restaurant = current_manager_restaurant_user.restaurant
    end
  end
end

app/views/manager/live/_order_items.html.erb
<% content_for :js do %>
  <script>
    $(function() {
      $(".receipt-ready").on('confirm:complete', function(e) {
        if (e.originalEvent.detail[0]) {
          var receiptId = this.id.match(/\d+/);
          $(`#receipt-${receiptId}-card`).hide();
        };
      });
    });
  </script>
<% end %> 

<% @restaurant = Restaurant.where(id: restaurant.id).first if @restaurant.blank? %>
<div class="row text-right">
  <div id="refreshed-time" class='col'>
    refreshed at: <%= Time.new.in_time_zone(@restaurant.time_zone).strftime("%d %b %Y - %H:%M:%S") %><%#= Time.new %>
  </div>
</div>

<div id="receipt-group" class="row m-2">
  <% @restaurant.receipts.where(is_ready: false, source: :takeaway).each do |receipt| %>
    <div id="receipt-<%= receipt.id %>-card" class="col-sm-6 mb-3">
      <div class="card">
        <div class="card-body">
          <div class="row m-2">
            <div class=" col">
              <% if receipt.delivery_or_collection != 'tableservice' %><h5 class="card-title">Name: <%=receipt.name%></h5><% end %>
              <% if receipt.delivery_or_collection != 'tableservice' %><h6 class="card-title">Time: <%=receipt.collection_time%></h6><% end %>
              <h6 class="card-title">Type: <%=receipt.delivery_or_collection%></h6>
              <% if receipt.delivery_or_collection == 'tableservice' %><h6 class="card-title">Table Number: <%=receipt.table_number%></h6><% end %>
              <% if receipt.telephone.present? %>  <h6 class="card-title">Telephone: <%=receipt.telephone%></h6><% end %>
              <% if receipt.delivery_or_collection == 'delivery' %> <h6 class="card-title">Address: <%=receipt.address%></h6><% end %>
            </div>
            <div class=" col-sm-5 text-right">
              <strong>Received: <%=receipt.created_at.in_time_zone(@restaurant.time_zone).strftime('%H:%M') %> </strong>
            </div>
          </div>
          <p class="card-text">
            <ul class="list-group">
              <% receipt.items['items'].each do |item| %>
                <li class="list-group-item">
                  <div class="row">
                    <div class="col"><%= item['item'].html_safe%></div>
                  </div>
                  <div class="row">
                    <div class="col"><small><%= item['optionals'].join('<br> ').html_safe%></small></div>
                  </div>
                  <% if item['note'].present? %>
                    <div class="row">
                      <div class="col"><strong>Note: </strong><%=item['note']%></div>
                    </div>
                  <% end %>
                </li>
              <% end %>
            </ul>
          </p>
          <% if receipt.order.refunds.present? %>
            <div class="btn btn-warning mt-3">Order has been refunded</div>
          <% else %>
            <%= link_to "Ready?",receipt_is_ready_path(receipt.id, only_path: true), method: :post, remote: true, class: 'btn btn-warning mt-3 receipt-ready', id: "receipt-#{receipt.id}-ready", data: { confirm: "Are your sure?" } %>
            <%= link_to "Refund",manager_refunds_path(restaurant_id: receipt.order.restaurant, id: receipt.order), method: :post, class: 'btn btn-info mt-3', data: { confirm: "Are your sure?" } if receipt.order.stripe_data.present? %>
          <% end %>
          <%= link_to "creation_broadcast",receipt_creation_broadcast_path(receipt.id, only_path: true), method: :post, remote: true, class: 'btn btn-danger mt-3' if Rails.env=='development' %>
          <% printers.each do |printer|%>
            <%# binding.pry %>
            <%= link_to "Print: #{printer.name}", print_receipt_url(receipt.id, printer.id, only_path: true), remote: true, class: 'btn btn-info  mt-3' %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/manager/live/_order_items_screen_specific.html.erb
<% content_for :js do %>
  <script>
    $(function() {
      $(".receipt-ready").on('confirm:complete', function(e) {
        if (e.originalEvent.detail[0]) {
          var receiptId = this.id.match(/\d+/);
          $(`#receipt-${receiptId}-card`).hide();
        };
      });
    });
  </script>
<% end %> 

<% @restaurant = Restaurant.find(restaurant) if @restaurant.blank? %>
<div class="row text-right">
  <div class='col'>
    refreshed at: <%= Time.new.in_time_zone(@restaurant.time_zone).strftime("%d %b %Y - %H:%M:%S") %><%#= Time.new %>
  </div>
</div>

<div id="receipt-group" class="row m-2">
  <% @screen_items = [] %>
  <% @screen_items = ScreenItem.where(ready: false, restaurant_id: @restaurant.id, item_screen_type_key: item_screen_type_key) if !grouped %>
  <% @screen_items = ScreenItem.where(ready: false, restaurant_id: @restaurant.id, item_screen_type_key: item_screen_type_key)  if grouped %>
  <% shown_receipts = [] %>
  <% @screen_items.each do |screen_item| %>
    <% receipt = screen_item.receipt if receipt.blank?%>
    <% unless shown_receipts.include?(screen_item.receipt_id) %>
      <% shown_receipts << screen_item.receipt_id %>
      <div id="receipt-<%= receipt.id %>-card" class="col-sm-6 mb-3">
        <div class="card">
          <div class="card-body">
            <% if receipt.delivery_or_collection != 'tableservice' %><h5 class="card-title">Name: <%=receipt.name%></h5><% end %>
            <% if receipt.delivery_or_collection != 'tableservice' %><h6 class="card-title">Time: <%=receipt.collection_time%></h6><% end %>
            <h6 class="card-title">Type: <%=receipt.delivery_or_collection%></h6>
            <% if receipt.delivery_or_collection == 'tableservice' %><h6 class="card-title">Table Number: <%=receipt.table_number%></h6><% end %>
            <% if receipt.telephone.present? %>  <h6 class="card-title">Telephone: <%=receipt.telephone%></h6><% end %>
            <% if receipt.delivery_or_collection == 'delivery' %> <h6 class="card-title">Address: <%=receipt.address%></h6><% end %>
            <%
              items = receipt.items['items'].select{|d| d['uuid'] == screen_item.uuid} if grouped == false
              items = receipt.items['items'].select{|d| d['item_screen_type_key'] == item_screen_type_key} if grouped == true
              items = receipt.items['items'].select{|d| d['secondary_item_screen_type_key'] == item_screen_type_key} if grouped == true if items.blank?
            %>  
            <% items.each do |item| %>
              <p class="card-text">
                <ul class="list-group">
                  <li class="list-group-item">
                    <div class="row">
                      <div class="col"><%= item['item'].html_safe%></div>
                    </div>
                    <div class="row">
                      <div class="col"><small><%= item['optionals'].join('<br> ').html_safe%></small></div>
                    </div>
                    <% if item['note'].present? %>
                      <div class="row">
                        <div class="col"><strong>Note: </strong><%=item['note']%></div>
                      </div>
                    <% end %>
                  </li>
                </ul>
              </p>
            <% end %>
            <%= link_to "Ready?",receipt_screen_item_ready_path(receipt.id, screen_item.id, only_path: true), method: :post, remote: true, class: 'btn btn-warning mt-3 receipt-ready', id: "receipt-#{receipt.id}-ready", data: { confirm: 'Are you sure?' } if !grouped %>
            <%= link_to "Ready?",receipt_screen_items_ready_path(receipt.id, item_screen_type_key: item_screen_type_key, only_path: true), method: :post, remote: true, class: 'btn btn-warning mt-3 receipt-ready', id: "receipt-#{receipt.id}-ready", data: { confirm: 'Are you sure?' } if grouped %>
            <%= link_to "Item_creation_broadcast",receipt_item_creation_broadcast_path(receipt.id, only_path: true), remote: true, method: :post, class: 'btn btn-danger mt-3' if Rails.env=='development' %>
            <% printers.each do |printer|%>
              <%# binding.pry %>
              <%= link_to "Print: #{printer.name}", print_item_receipt_path(receipt.id, screen_item.uuid, printer.id, only_path: true), remote: true, class: 'btn btn-info  mt-3' if !grouped  %>
              <% printer_key = printer.item_screens.first.item_screen_type_key if printer.item_screens.present? %>
              <% if  printer_key == item_screen_type_key %>
                <%= link_to "Print: #{printer.name}", print_items_receipt_path(receipt.id, printer.id, item_screen_type_key: item_screen_type_key, only_path: true), remote: true, class: 'btn btn-info  mt-3'  if grouped %>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/manager/live/items.html.erb
<div class="container-fluid mt-5 mb-2">
  <div class="row m-2">


        <% @restaurant_tables.each do |restaurant_table| %>
          <% restaurant_table.tables_live.each do |table|%>
            <% if table.has_live_items? %>
              <div class=" col-sm-3">
              <div class="card">
                <div class="card-body">
                  <h5 class="card-title">Table Number: <%=table.restaurant_table_number%></h5>               
                  <p class="card-text">
                    <ul class="list-group">
                      <% table.live_items.order(:created_at).each do |item| %>
                        <li class="list-group-item">
                            <div class="row">
                              <div class="col"><%= item.name%></div>
                              <div class='col text-right'><%= item.aasm_state %></div>
                            </div>
                            <% item.custom_lists.keys.each do |list_id| %>
                              <% begin %>
                              <% custom_list = CustomList.find(list_id) %>
                                <% item.custom_lists[list_id].each do |list_item_id| %>
                                  <% list_item = CustomListItem.find(list_item_id) %>
                                  <div class="row">
                                    <div class="col">- <%= "#{custom_list.name}: #{list_item.name}" %></div>
                                  </div>
                                <% end %>
                              <% rescue
                              end%>
                            <% end %>
                            <%=%>
                            <%= link_to "Service",manager_live_service_path(table.restaurant.id, item.id), class: 'btn btn-warning mt-3', data: { confirm: 'Are you sure?' } if item.aasm_state=='ordered' %>
                            <%= link_to "Ready?",manager_live_ready_path(table.restaurant.id, item.id), class: 'btn btn-warning mt-3', data: { confirm: 'Are you sure?' } if item.aasm_state=='paid' %>
                        </li>
                      <% end %>
                    </ul>
                  </p>
                  <!--  -->
                  <!-- <a href="#" class="card-link">Another link</a> -->
                </div>
              </div>
              </div>
            <% end %>

          <% end %>
        <% end %>
        





  </div>
</div>